#ifndef TOURNAMENT_GRID_GENERATOR_GRIDMANAGER_H
#define TOURNAMENT_GRID_GENERATOR_GRIDMANAGER_H

#include "include/Stdaf.h"

class GridManager {
private:
public:
};

#endif //TOURNAMENT_GRID_GENERATOR_GRIDMANAGER_H