#ifndef TOURNAMENT_GRID_GENERATOR_LOGICPROGRAM_H
#define TOURNAMENT_GRID_GENERATOR_LOGICPROGRAM_H

#include "Windows.h"

class LogicProgram {
public:

};

#endif //TOURNAMENT_GRID_GENERATOR_LOGICPROGRAM_H
