#ifndef TOURNAMENT_GRID_GENERATOR_TEAMGRAPH_H
#define TOURNAMENT_GRID_GENERATOR_TEAMGRAPH_H

#include "Stdaf.h"

class TeamGraph {
private:
public:
};


#endif //TOURNAMENT_GRID_GENERATOR_TEAMGRAPH_H
